### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by creack** [MaxCDN/go-maxcdn#5]
Having a `-` in the repository name is not ideal, it messes with editors completion / tag lookup and forces the developer to use a named import.

Renaming the repositoty in `gomaxcdn` would be great. Github will keep the redirect from `go-maxcdn` to `gomaxcdn` so it will not impact people using the current name.

**Comment by creack** [comment]
An alternative would be to move everything under a `maxcdn` subdir.

**Comment by jmervine** [comment]
I need to verify that github redirects work when using `go get` before renaming this. I can't break backwards compatibility. (cc @jdorfman)

**Comment by jdorfman** [comment]
This is a tough one.  Let me check with a few people first.
