### ISSUE TITLE
Use gopkg.in

### ISSUE THREAD

**Issue by creack** [MaxCDN/go-maxcdn#6]
Has maxcdn provides this package for an API implementation, it would be interesting to use http://gopkg.in instead of standard `go get github.com/..`

The idea is to have a tag per stable api. If tomorrow you decide to update your API, the legacy one would still be available.

Example: http://gopkg.in/mgo.v2

**Comment by jmervine** [comment]
Been meaning to do this, thanks for reminding me. :-)

**Comment by jmervine** [comment]
Done
